// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/componere/incus-guest-agent/internal/agent"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeviceFinder creates a new instance of MockDeviceFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceFinder {
	mock := &MockDeviceFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeviceFinder is an autogenerated mock type for the DeviceFinder type
type MockDeviceFinder struct {
	mock.Mock
}

type MockDeviceFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceFinder) EXPECT() *MockDeviceFinder_Expecter {
	return &MockDeviceFinder_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockDeviceFinder
func (_mock *MockDeviceFinder) Find(ctx context.Context) ([]agent.DevicePath, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []agent.DevicePath
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]agent.DevicePath, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []agent.DevicePath); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]agent.DevicePath)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceFinder_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockDeviceFinder_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDeviceFinder_Expecter) Find(ctx any) *MockDeviceFinder_Find_Call {
	return &MockDeviceFinder_Find_Call{Call: _e.mock.On("Find", ctx)}
}

func (_c *MockDeviceFinder_Find_Call) Run(run func(ctx context.Context)) *MockDeviceFinder_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeviceFinder_Find_Call) Return(devicePaths []agent.DevicePath, err error) *MockDeviceFinder_Find_Call {
	_c.Call.Return(devicePaths, err)
	return _c
}

func (_c *MockDeviceFinder_Find_Call) RunAndReturn(run func(ctx context.Context) ([]agent.DevicePath, error)) *MockDeviceFinder_Find_Call {
	_c.Call.Return(run)
	return _c
}
