// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/componere/incus-guest-agent/internal/agent"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStageManager creates a new instance of MockStageManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStageManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStageManager {
	mock := &MockStageManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStageManager is an autogenerated mock type for the StageManager type
type MockStageManager struct {
	mock.Mock
}

type MockStageManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStageManager) EXPECT() *MockStageManager_Expecter {
	return &MockStageManager_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function for the type MockStageManager
func (_mock *MockStageManager) Cleanup(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStageManager_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockStageManager_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStageManager_Expecter) Cleanup(ctx any) *MockStageManager_Cleanup_Call {
	return &MockStageManager_Cleanup_Call{Call: _e.mock.On("Cleanup", ctx)}
}

func (_c *MockStageManager_Cleanup_Call) Run(run func(ctx context.Context)) *MockStageManager_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStageManager_Cleanup_Call) Return(err error) *MockStageManager_Cleanup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStageManager_Cleanup_Call) RunAndReturn(run func(ctx context.Context) error) *MockStageManager_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// Stage provides a mock function for the type MockStageManager
func (_mock *MockStageManager) Stage(ctx context.Context, device agent.DevicePath) error {
	ret := _mock.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for Stage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, agent.DevicePath) error); ok {
		r0 = returnFunc(ctx, device)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStageManager_Stage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stage'
type MockStageManager_Stage_Call struct {
	*mock.Call
}

// Stage is a helper method to define mock.On call
//   - ctx context.Context
//   - device agent.DevicePath
func (_e *MockStageManager_Expecter) Stage(ctx any, device any) *MockStageManager_Stage_Call {
	return &MockStageManager_Stage_Call{Call: _e.mock.On("Stage", ctx, device)}
}

func (_c *MockStageManager_Stage_Call) Run(run func(ctx context.Context, device agent.DevicePath)) *MockStageManager_Stage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 agent.DevicePath
		if args[1] != nil {
			arg1 = args[1].(agent.DevicePath)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStageManager_Stage_Call) Return(err error) *MockStageManager_Stage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStageManager_Stage_Call) RunAndReturn(run func(ctx context.Context, device agent.DevicePath) error) *MockStageManager_Stage_Call {
	_c.Call.Return(run)
	return _c
}
